# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FleetPlayer' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FleetPlayer

  pod 'MMDrawerController', '~> 0.5.7'
  target 'FleetPlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FleetPlayerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
